import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/getstarted.module.css'
import Link from 'next/link'

export default function Activites() {
  return (
    <>
      <Head>
        <title>Activites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Image src='/Logo/stacklogo.svg' width='550' height='400' className={styles.logo}/>
        <p className={styles.quote}>"Join the fight against fire hazards with Heat Help - The ultimate fire safety app!"</p>
        <p className={styles.description}>
          Heat Help is the ultimate fire safety app designed to educate and equip you with the knowledge necessary to prevent fires and respond to emergencies. Wherever you go, Heat Help has got you covered.
        </p>
      </main>
    </>
  )
}
