import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/learningInCaseOfAFire.module.css'
import ReturnIcon from '@/components/returnIcon'

export default function LearningInCaseOfAFire() {
    return (
        <>
            <Head>
                <title>Learning In Case Of A Fire</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href='/learning'><ReturnIcon /></Link>
            <main className={styles.main}>
                <div className={styles.box}>
                    <h1>Fire Action</h1>
                    <h2>If you discover or suspect a fire</h2>
                </div>

                <div className={styles.box2}>
                    <h1>1.</h1>
                    <h2>Operate the nearest fire alarm call point</h2>
                </div>

                <div className={styles.box3}>
                    <h1>2.</h1>
                    <h2>leave the building by the nearest available exit</h2>
                </div>

                <div className={styles.box3}>
                    <h1>3.</h1>
                    <h2>Report to person in charge of Assembly point</h2>
                </div>

                <div className={styles.box2}>
                    <h1>4.</h1>
                    <h2>Do not stop to collect personal belongings</h2>
                </div>
            </main>
        </>
    )
}

