import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/learningInCaseOfAFire.module.css'
import ReturnIcon from '@/components/returnIcon'

export default function LearningInCaseOfAFire() {
    return (
        <>
            <Head>
                <title>Learning In Case Of A Fire</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href='/learning'><ReturnIcon /></Link>
            <main className={styles.main}>
                <h3>What to do in case of a fire?</h3>
                <div className={styles.flex}>
                    <div>
                        <Image src='/imagery/in-case-of-a-fire/fire exit.jpg' width='150' height='100' />
                        <p>Find the nearest EXIT</p>
                    </div>

                    <div>
                        <Image src='/imagery/in-case-of-a-fire/use exit.jpg' width='150' height='200' />
                        <p>Use Stairs in stead of Lift</p>
                    </div>
                </div>

                <div>
                    <Image src='/imagery/in-case-of-a-fire/fire action.jpg' width='320' height='350' />
                    <p>Use Stairs in stead of Lift</p>
                </div>
            </main>
        </>
    )
}

