import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/learning3FireType.module.css'
import ReturnIcon from '@/components/returnIcon'
import Bluebutton from '@/components/Bluebutton'
import Button from '@/components/Button'
import Redbutton from '@/components/Redbutton'


export default function LearningOrdinary() {
    return (
      <>
        <Head>
          <title>Learning about Ordinary Fire</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Link href='/learning'><ReturnIcon/></Link>


        <main className={styles.main}>               
            <h1>Learn about Ordinary Fire</h1>
            <img src='/illustrations/ordinary fire.svg' className={styles.illustration} />   
            <p className={styles.description}>An ordinary fire refers to a standard fire that occurs when a combustible material, such as wood, paper, fabric, or other flammable substances, comes into contact with a heat source and reaches its ignition point. </p>
            <p className={styles.description}>Basically, ordinary fire occur from fire place and any kitchen facilities.</p>
            <Image src='/imagery/fire-causes/kid-with-fire.jpg' width='350' height='200'/>
            <p className={styles.description}>Ordinary fires can typically be extinguished using appropriate fire extinguishing methods, such as water, fire extinguishers, fire blankets, or other extinguishing agents, depending on the type of fuel and the size and location of the fire. The appropriate fire extinguishing method should be chosen based on the type of fire to avoid making the situation worse.</p>            
            <p className={styles.description2}>Proper fire prevention measures, such as using caution with open flames, maintaining electrical systems in good condition, handling flammable materials safely, and practicing safe smoking habits, can help prevent ordinary fires from occurring.</p>

            <div className={styles.buttons}>
                <Redbutton>Take the quiz</Redbutton>
                <Link href='/learningElectric'><Bluebutton>Start again from Electrical Fires ⮞</Bluebutton></Link>
                
            </div>
            
          
        </main>
      </>
    )
  }