import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Quizzes.module.css'

export default function Login() {
  return (
    <>
      <Head>
        <title>Quizzes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.quizcontainer}>
            <Image src='/illustrations/electric fire.svg' width='200' height='200' className={styles.illustration}/>

        </div>

      </main>
    </>
  )
}
