import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Quizzes.module.css'
import Bluebutton from '@/components/Bluebutton'

export default function Quizzes() {
  return (
    <>
      <Head>
        <title>Quizzes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Quizzes</h1>
        <h2>Try one of our quizzes to asses your knowledge on different kinds of fires!</h2>
        <div className={styles.threeoptions}>
            <div className={styles.quizcontainer}>
                <img src='/illustrations/electric fire.svg' className={styles.illustration}/>
                <Bluebutton>Electrical Fire</Bluebutton>
            </div>
            <div className={styles.quizcontainer}>
                <img src='/illustrations/grease fire.svg' className={styles.illustration}/>
                <Bluebutton>Grease Fire</Bluebutton>
            </div>
            <div className={styles.quizcontainer}>
                <img src='/illustrations/ordinary fire.svg' className={styles.illustration}/>
                <Bluebutton>Ordinary Fire</Bluebutton>
            </div>

        </div>

      </main>
    </>
  )
}
