import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/resources.module.css'

export default function Resources() {
  return (
    <>
      <Head>
        <title>Resources</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Resources</h1>
        <h3>Vancouver fire and rescue services map</h3>
        <Image src='/imagery/service-map.png' width='350' height='230' />
        <h3>Fire emergency: 911</h3>
        <div className={styles.description}>
          <div>
            <h4><b>Vancouver Fire & Radius Security:</b></h4>
            <ul>
              <li><b>Phone: </b> 604.232.3473</li>
              <li><b>Website: </b> https://www.vanfire.com/</li>
            </ul>
          </div>

          <div>
            <h4><b>Fire Protection Association:</b></h4>
            <ul>
              <li><b>Phone: </b> 617.984.7275</li>
              <li><b>Website: </b> https://www.nfpa.org/</li>
            </ul>
          </div>

          <div>
            <h4><b>Fire services, standards and reporting:</b> </h4>
            <p className={styles.flex}>https://www2.gov.bc.ca/gov/content/safety/emergency-management/fire-safety</p>
          </div>

          <div className={styles.flex}>
            <Image src='/imagery/fire-fighter.jpg' width='150' height='90'/>
            <Image src='/imagery/fire-truck.jpg' width='150' height='90'/>
          </div>
        </div>
      </main>
    </>
  )
}

