import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/resources.module.css';
import Link from 'next/link';
import ResourcesButton from '@/components/ResourcesButton';
import ResourcesButtonv2 from '@/components/ResourcesButtonv2';
import { useState, useRef, useEffect } from 'react';
import Map from '../components/Map'

export default function Resources() {
  const [accordion1, setAccordion1] = useState(false);
  const [accordion2, setAccordion2] = useState(false);
  const [accordion3, setAccordion3] = useState(false);
  const [accordion4, setAccordion4] = useState(false);
  const accordionRef1 = useRef();
  const accordionRef2 = useRef();
  const accordionRef3 = useRef();
  const accordionRef4 = useRef();

  const toggleAccordion1 = () => setAccordion1(!accordion1);
  const toggleAccordion2 = () => setAccordion2(!accordion2);
  const toggleAccordion3 = () => setAccordion3(!accordion3);
  const toggleAccordion4 = () => setAccordion4(!accordion4);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (
        accordionRef1.current &&
        !accordionRef1.current.contains(event.target) &&
        accordion1
      ) {
        setAccordion1(false);
      }
      if (
        accordionRef2.current &&
        !accordionRef2.current.contains(event.target) &&
        accordion2
      ) {
        setAccordion2(false);
      }
      if (
        accordionRef3.current &&
        !accordionRef3.current.contains(event.target) &&
        accordion3
      ) {
        setAccordion3(false);
      }
      if (
        accordionRef4.current &&
        !accordionRef4.current.contains(event.target) &&
        accordion4
      ) {
        setAccordion4(false);
      }
    };
  
    document.addEventListener('mousedown', handleClickOutside);
  
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [accordion1, accordion2, accordion3, accordion4]);

  return (
    <>
      <Head>
        <title>Resources</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <h1>Resources</h1>
          <Image src="/icons/pagesIcon/resources icon.svg" width="200" height="150" />
          <h3 className={styles.flex}>Vancouver fire and rescue services map</h3>
          <Map/>
          <div className={styles.description}>
            <div className={styles.resourcescontainer} ref={accordionRef1}>
              <ResourcesButtonv2 onClick={toggleAccordion1}>
                <h4>
                  <b>Fire Information for Resource Managamenent System US/Canada</b>
                </h4>
              </ResourcesButtonv2>
              {accordion1 && (
                <div className={styles.panel}>
                  <p className={styles.paragraph}>
                 
                    The information provided on the FIRMS webpage, including the US/Canada section, is gathered from various satellite and ground-based sources and updated every few hours. Overall, the FIRMS webpage is an essential tool for anyone interested in staying informed about fire activity and its management.
                  </p>
                  <Link href="https://firms.modaps.eosdis.nasa.gov/usfs/map/#d:2023-05-13..2023-05-14,2023-05-13;l:landsat,noaa20-viirs,viirs,modis_a,modis_t,active-usa,fire-perimeter;@-107.9,49.3,5z">
                    <ResourcesButton>
                      <b>Website</b>
                    </ResourcesButton>
                  </Link>
                </div>
              )}
            </div>
            
            <div className={styles.resourcescontainer} ref={accordionRef2}>
              <ResourcesButtonv2 onClick={toggleAccordion2}>
                <h4>
                  <b>Canadian Interagency Forest Fire Centre</b>
                </h4>
              </ResourcesButtonv2>
              {accordion2 && (
                <div className={styles.panel}>
                  <h4></h4>
                  <p className={styles.paragraph}>
                    The CIFFC coordinates resource sharing, mutual aid, and information among federal, provincial, and territorial wildland fire management agencies. It also facilitates national and international cooperation in fire management planning, program delivery, and human resource strategies.</p>
                  <p>
                    <b>Phone: 204-784-2030</b>
                  </p>
                  <Link href="https://www.ciffc.ca/">
                    <ResourcesButton>
                      <b>Website</b>
                    </ResourcesButton>
                  </Link>
                </div>
              )}
            </div>

            <div className={styles.resourcescontainer} ref={accordionRef3}>
              <ResourcesButtonv2 onClick={toggleAccordion3}>
                <h4>
                  <b>BC Wild Fire Services</b>
                </h4>
              </ResourcesButtonv2>
              {accordion3 && (
                <div className={styles.panel}>
                  <h4></h4>
                  <p className={styles.paragraph}>
                    
                  The BC Wildfire Service manages wildfires in British Columbia. They employ personnel to detect and respond to around 1,600 wildfires per year. The organization is divided into six regional fire centers with fire zones. Employment and contract opportunities are available. The website provides governance information, wildfire history summaries, statistics, geospatial data, and a glossary of terms.</p>
                  <p>
                  <b>Report a wildfire: 1-800-663-5555 or *5555 on a cell</b>
                  </p>
                  <p>
                  <b>Fire information line: 1-888-336-7378</b>
                  </p>
                  <p>
                  <b>Burn registration line: 1-888-797-1717</b>
                  </p>
                  <Link href="https://www2.gov.bc.ca/gov/content/safety/wildfire-status">
                    <ResourcesButton>
                      <b>Website</b>
                    </ResourcesButton>
                  </Link>
                </div>
              )}
            </div>

            <div className={styles.resourcescontainer} ref={accordionRef4}>
              <ResourcesButtonv2 onClick={toggleAccordion4}>
                <h4>
                  <b>Fire services, standards and reporting:</b>
                </h4>
              </ResourcesButtonv2>
              {accordion4 && (
                <div className={styles.panel }>
                  <p>The Office of the Fire Commissioner (OFC) provides:</p>
                  <ul>
                    <li>Applicable legislation and codes</li>
                    <li>Firefighter standards and training</li>
                    <li>Fire incident reporting</li>
                    <li>Local Assistant to the Fire Commissioner (LAFC)</li>
                    <li>Fire service awards</li>
                  </ul>
                  <Link href="https://www2.gov.bc.ca/gov/content/safety/emergency-management/fire-safety ">
                    <ResourcesButton>
                      <b>Website</b>
                    </ResourcesButton>
                  </Link>
                </div>
              )}
            </div>
            
          </div>
        </div>
      </main>
    </>
  );
}
