import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/tutorial.module.css'
import Carousel from '@/components/Carousel'
import Link from 'next/link'
import Video from '@/components/VideoPlayer'

export default function Tutorial() {
  return (
    <>
      <Head>
        <title>Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <h1>Tutorial</h1>
          <Image src='/icons/pagesIcon/tutorial icon.svg' width='150' height='150' />
          <Video/>

          <ol className={styles.description}>
            <li>
              Navigate to the <Link href='/learning'><span> Learning Page </span></Link> and press the button about the fire
              in the field you want to know about.
            </li>

            <li>
              Navigate to the <Link href='/learning'><span> Quiz Page </span></Link> to learn about various types of fire through
              quizzes. If you choose the wrong option,
              you will get feedback.
            </li>

            <li>
              Navigate to the <Link href='/learning'><span> About Page </span></Link> to learn more about our team
            </li>

            <li>
              Navigate to the <Link href='/learning'><span> Resources Page </span></Link> to find out more helpful page that can help you gain more knowledge about fire safety
            </li>

          </ol>

          <h3>App Interface Overview</h3>
          <Carousel />

        </div>
      </main>
    </>
  )
}

