import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/tutorial.module.css'
import Carousel from '@/components/Carousel'

export default function Tutorial() {
  return (
    <>
      <Head>
        <title>Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <h1>Tutorial</h1>
          <Image src='/icons/pagesIcon/tutorial icon.svg' width='150' height='150' />
          <img src='https://d2uolguxr56s4e.cloudfront.net/img/kartrapages/video_player_placeholder.gif' width='350' height='230' />

          <ol className={styles.description}>
            <li>
              Press the button about the fire
              in the field you want to know about.
            </li>
            <li>
              Learn about various types of fire through
              quizzes. If you choose the wrong option,
              you will get feedback.
            </li>
          </ol>

          <h3>App Interface Overview</h3>
          <Carousel/>

        </div>
      </main>
    </>
  )
}

